
from . import _lib
from ._lib import Kernel, SchemaHolder, ArrayHolder, CVectorType


class GeometryType:
    GEOMETRY = _lib.GEOARROW_GEOMETRY_TYPE_GEOMETRY
    POINT = _lib.GEOARROW_GEOMETRY_TYPE_POINT
    LINESTRING = _lib.GEOARROW_GEOMETRY_TYPE_LINESTRING
    POLYGON = _lib.GEOARROW_GEOMETRY_TYPE_POLYGON
    MULTIPOINT = _lib.GEOARROW_GEOMETRY_TYPE_MULTIPOINT
    MULTILINESTRING = _lib.GEOARROW_GEOMETRY_TYPE_MULTILINESTRING
    MULTIPOLYGON = _lib.GEOARROW_GEOMETRY_TYPE_MULTIPOLYGON
    GEOMETRYCOLLECTION = _lib.GEOARROW_GEOMETRY_TYPE_GEOMETRYCOLLECTION

class Dimensions:
    UNKNOWN = _lib.GEOARROW_DIMENSIONS_UNKNOWN
    XY = _lib.GEOARROW_DIMENSIONS_XY
    XYZ = _lib.GEOARROW_DIMENSIONS_XYZ
    XYM = _lib.GEOARROW_DIMENSIONS_XYM
    XYZM = _lib.GEOARROW_DIMENSIONS_XYZM

class CoordType:
    UNKNOWN = _lib.GEOARROW_COORD_TYPE_UNKNOWN
    SEPARATE = _lib.GEOARROW_COORD_TYPE_SEPARATE
    INTERLEAVED = _lib.GEOARROW_COORD_TYPE_INTERLEAVED

class EdgeType:
    PLANAR = _lib.GEOARROW_EDGE_TYPE_PLANAR
    SPHERICAL = _lib.GEOARROW_EDGE_TYPE_SPHERICAL

class CrsType:
    NONE = _lib.GEOARROW_CRS_TYPE_NONE
    UNKNOWN = _lib.GEOARROW_CRS_TYPE_UNKNOWN
    PROJJSON = _lib.GEOARROW_CRS_TYPE_PROJJSON
