name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yaml'
      - 'ci/scripts/build-docs.sh'
      - 'docker-compose.yml'
      - 'src/**'
      - 'docs/source/**'

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build documentation
        run: |
          echo "::group::Docker Pull"
          docker compose run --rm -e GITHUB_ACTIONS docs

      - name: Upload built documentation
        uses: actions/upload-artifact@main
        with:
          name: geoarrow-docs
          path: docs/_build/html

      - name: Clone gh-pages branch
        if: success() && github.repository == 'geoarrow/geoarrow-c' && github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages-clone

      - name: Update development documentation
        if: success() && github.repository == 'geoarrow/geoarrow-c' && github.ref == 'refs/heads/main'
        env:
          DOC_TAG: "dev"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd pages-clone
          if [ -d "$DOC_TAG" ]; then
            git rm -rf "$DOC_TAG"
          fi
          mkdir "$DOC_TAG"
          cp -R ../docs/_build/html/* "$DOC_TAG"
          touch .nojekyll
          git add .nojekyll
          git add *
          git commit --allow-empty -m"update documentation for tag $DOC_TAG"
          git push
          cd ..
