name: test-python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/python.yaml'
      - 'src/geoarrow/**'
      - 'python/**'

jobs:
  test-python:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install geoarrow
        run: |
          pushd python/geoarrow-c
          pip install .[test]
          popd
          pip list

      - name: Run tests
        run: |
          pytest python/geoarrow-c/tests -v -s

      - name: Run doctests
        if: success() && matrix.python-version == '3.10'
        run: |
          pytest --pyargs geoarrow --doctest-modules
          # No Cython docs yet
          # pip install pytest-cython
          # pytest --pyargs geoarrow --doctest-cython

      - name: Coverage
        if: success() && matrix.python-version == '3.10'
        run: |
          sudo apt-get install -y lcov
          pip uninstall --yes geoarrow
          pip install pytest-cov Cython
          pushd python/geoarrow-c

          # Build with Cython + gcc coverage options
          pip install -e .[test]
          GEOARROW_COVERAGE=1 python3 setup.py build_ext --inplace

          # Run tests + coverage.py (generates .coverage + coverage.xml files)
          python -m pytest --cov ./src/geoarrow
          python -m coverage xml

          # Collect C coverage information
          lcov \
            --capture --directory build \
            --exclude "/usr/*" \
            --exclude "/Library/*" \
            --exclude "*/_lib.cpp" \
            --exclude "*/src/geoarrow/geoarrow/*" \
            --output-file=coverage.info

          lcov --list coverage.info

      - name: Upload coverage to codecov
        if: success() && matrix.python-version == '3.10'
        uses: codecov/codecov-action@v2
        with:
          files: 'python/geoarrow-coverage.info,python/geoarrow-c/coverage.xml'
